"""empty message

Revision ID: cbb0b7ee95b3
Revises: 76358e6c1333
Create Date: 2022-02-08 15:36:46.339619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb0b7ee95b3'
down_revision = '76358e6c1333'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sensorfeed_sensor_id_fkey', 'sensorfeed', type_='foreignkey')
    op.create_foreign_key(None, 'sensorfeed', 'sensor', ['sensor_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sensorfeed', type_='foreignkey')
    op.create_foreign_key('sensorfeed_sensor_id_fkey', 'sensorfeed', 'sensor', ['sensor_id'], ['id'])
    # ### end Alembic commands ###
